name: Build and deploy code

on: push

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: pulling get repo
              uses: actions/checkout@v7.0.1
            - name: tell him its working
              run: echo "iTS woRKING"